### ISSUE TITLE
An error occurs in console application 'Invalid path alias: @webroot/assets'

### ISSUE THREAD

**Issue by vsivsivsi** [pistol88/yii2-filter#4]
An error occurs in console application after install this extension:
```
$ yii
Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @webroot/assets'

in D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\BaseYii.php:152

Stack trace:
#0 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\web\AssetManager.php(211): yii\BaseYii::getAlias('@webroot/assets')
#1 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\base\Object.php(107): yii\web\AssetManager->init()
#2 [internal function]: yii\base\Object->__construct(Array)
#3 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\di\Container.php(375): ReflectionClass->newInstanceArgs(Array)
#4 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\web\\AssetMa...', Array, Array)
#5 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\BaseYii.php(344): yii\di\Container->get('yii\\web\\AssetMa...', Array, Array)
#6 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\di\ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#7 D:\OpenServer\domains\pistol.loc\vendor\pistol88\yii2-filter\Bootstrap.php(10): yii\di\ServiceLocator->get('assetManager')
#8 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\base\Application.php(296): pistol88\filter\Bootstrap->bootstrap(Object(yii\console\Application))
#9 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\base\Application.php(272): yii\base\Application->bootstrap()
#10 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\console\Application.php(124): yii\base\Application->init()
#11 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\base\Object.php(107): yii\console\Application->init()
#12 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\base\Application.php(205): yii\base\Object->__construct(Array)
#13 D:\OpenServer\domains\pistol.loc\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#14 D:\OpenServer\domains\pistol.loc\yii(26): yii\console\Application->__construct(Array)
#15 {main} 
```

**Comment by pistol88** [comment]
`Yii::setAlias('@webroot', 'path to web directory');`

to console config.
